nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - /etc/letsencrypt/live/yourdomain.com/fullchain.pem:/etc/nginx/certs/fullchain.pem
    - /etc/letsencrypt/live/yourdomain.com/privkey.pem:/etc/nginx/certs/privkey.pem
    - /home/adminramses/src/nginx/conf.d:/etc/nginx/conf.d
